version: '3'
services:
  golang:
    image: xgopher/golang:1.12
    container_name: xgopher_golang
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
    stdin_open: true
    tty: true
    restart: always
